services:
  postgres:
    image: postgres:17
    restart: unless-stopped # <-- این خط را اضافه کنید
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: lmsdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
